{% set name = "scalapack" %}
{% set version = "2.0.2" %}
{% set sha256 = "0c74aeae690fe5ee4db7926f49c5d0bb69ce09eea75beb915e00bba07530395c" %}

{% set mpi = mpi or 'mpich' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.netlib.org/{{ name }}/{{ name }}-{{ version }}.tgz
  sha256: {{ sha256 }}
  patches:
    - 0001-mpi3.patch
    - 0002-cmake.patch

build:
  number: 1010
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - make
  host:
    - libblas
    - liblapack
    - {{ mpi }}
  run:
    - {{ mpi }}

test:
  commands:
    - test -f $PREFIX/lib/libscalapack.dylib  # [osx]
    - test -f $PREFIX/lib/libscalapack.so  # [linux]

about:
  home: http://www.netlib.org/scalapack/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ScaLAPACK is a library of high-performance linear algebra routines for parallel distributed memory machines
  description: |
    ScaLAPACK is a library of high-performance linear algebra routines for parallel distributed
    memory machines. ScaLAPACK solves dense and banded linear systems, least squares problems,
    eigenvalue problems, and singular value problems.

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
